# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from random import choice
import sys
import pandas as pd
from os import remove
names = []
cols = [-1, 8, 7, 5, 4, 3, 1, 0]
header_labels = ['A', 'B']

YELLOW = QtGui.QPalette()
YELLOW.setColor(QtGui.QPalette.Base, QtCore.Qt.yellow)
NULL = QtGui.QPalette()


def idtoname(id):
    group = ""
    num = ""
    for i in id:
        try:
            _ = int(i)
            num += i
        except:
            group += i
    if group in header_labels:
        group = header_labels.index(group)
        try:
            num = int(num)-1
        except:
            return float("nan")
        try:
            return names[num][group]
        except:
            return float("nan")
    else:
        return float("nan")

class Ui_MainWindow(object):
    listname = "test.xlsx"
    seats = [(i, j) for i in range(1, 8) for j in range(1, 8)]
    mnu = [(i, j) for i in range(1, 8) for j in range(1, 8)]
    cpy = list(mnu)
    _slst = ["nan"]
    slst = ["nan"]
    dir = ""
    def setupUi(self, MainWindow):
        global names, cols, header_labels
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 720)
        self.fnt = QtGui.QFont()
        self.fnt.setPointSize(13)
        MainWindow.setFont(self.fnt)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setMinimumSize(QtCore.QSize(0, 0))
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.group = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group.sizePolicy().hasHeightForWidth())
        self.group.setSizePolicy(sizePolicy)
        self.group.setMinimumSize(QtCore.QSize(0, 0))
        self.group.setEditable(False)
        self.group.setObjectName("group")
        self.group.addItem("")
        self.group.addItem("")
        self.horizontalLayout_3.addWidget(self.group)
        self.id = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id.sizePolicy().hasHeightForWidth())
        self.id.setSizePolicy(sizePolicy)
        self.id.setMinimumSize(QtCore.QSize(0, 0))
        self.id.setMinimum(1)
        self.id.setSingleStep(1)
        self.id.setObjectName("id")
        self.horizontalLayout_3.addWidget(self.id)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.row = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.row.sizePolicy().hasHeightForWidth())
        self.row.setSizePolicy(sizePolicy)
        self.row.setDigitCount(1)
        self.row.setObjectName("row")
        self.horizontalLayout_2.addWidget(self.row)
        self.col = QtWidgets.QLCDNumber(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col.sizePolicy().hasHeightForWidth())
        self.col.setSizePolicy(sizePolicy)
        self.col.setDigitCount(1)
        self.col.setObjectName("col")
        self.horizontalLayout_2.addWidget(self.col)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 2, 0, 1, 1)
        self.filename = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filename.sizePolicy().hasHeightForWidth())
        self.filename.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.filename.setFont(font)
        self.filename.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 4, 2, 1, 1)
        self.reset = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        self.reset.setObjectName("reset")
        self.gridLayout.addWidget(self.reset, 4, 0, 1, 1)
        self.output = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 5, 0, 1, 1)
        self.draw = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.draw.sizePolicy().hasHeightForWidth())
        self.draw.setSizePolicy(sizePolicy)
        self.draw.setObjectName("draw")
        self.gridLayout.addWidget(self.draw, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        for col in range(1, 8):
            exec(f"""
self.Col{col} = QtWidgets.QVBoxLayout()
self.Col{col}.setObjectName("Col{col}")
            """)
            for row in range(1, 8):
                exec(f"""
self.L{col}{row} = QtWidgets.QLineEdit(self.groupBox)
sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
sizePolicy.setHorizontalStretch(0)
sizePolicy.setVerticalStretch(0)
sizePolicy.setHeightForWidth(self.L{col}{row}.sizePolicy().hasHeightForWidth())
self.L{col}{row}.setSizePolicy(sizePolicy)
self.L{col}{row}.setReadOnly(True)
self.L{col}{row}.setObjectName("L{col}{row}")
self.L{col}{row}.setAlignment(QtCore.Qt.AlignCenter)
self.Col{col}.addWidget(self.L{col}{row})
                """)
            exec(f"self.gridLayout_3.addLayout(self.Col{col}, 1, {cols[col]}, 1, 1)")

        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 9)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 6, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 4, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        #self.jump = QtWidgets.QCheckBox(self.tab)
        #self.jump.setObjectName("jump")
        #self.jump.setDisabled(True)
        #self.horizontalLayout_4.addWidget(self.jump)
        self.progress = QtWidgets.QLabel(self.tab)#QProgressBar(self.tab)
        #self.progress.setProperty("value", 0)
        #self.progress.setTextVisible(False)
        self.progress.setObjectName("progress")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress.sizePolicy().hasHeightForWidth())
        self.progress.setSizePolicy(sizePolicy)
        self.horizontalLayout_4.addWidget(self.progress)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 1, 1, 3)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(2, 5)
        self.gridLayout.setRowStretch(0, 5)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(4, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pix = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pix.sizePolicy().hasHeightForWidth())
        self.pix.setSizePolicy(sizePolicy)
        self.pix.setMinimum(12)
        self.pix.setMaximum(96)
        self.pix.setSingleStep(1)
        self.pix.setDisplayIntegerBase(10)
        self.pix.setObjectName("pix")
        self.gridLayout_6.addWidget(self.pix, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.font = QtWidgets.QFontComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.font.sizePolicy().hasHeightForWidth())
        self.font.setSizePolicy(sizePolicy)
        self.font.setObjectName("font")
        self.gridLayout_6.addWidget(self.font, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        self.art = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.art.sizePolicy().hasHeightForWidth())
        self.art.setSizePolicy(sizePolicy)
        self.art.setObjectName("art")
        self.art.addItem("")
        self.gridLayout_6.addWidget(self.art, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.dldir = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dldir.sizePolicy().hasHeightForWidth())
        self.dldir.setSizePolicy(sizePolicy)
        self.dldir.setReadOnly(True)
        self.dldir.setObjectName("dldir")
        self.gridLayout_7.addWidget(self.dldir, 0, 1, 1, 1)
        self.changedir = QtWidgets.QPushButton(self.groupBox_4)
        self.changedir.setObjectName("changedir")
        self.gridLayout_7.addWidget(self.changedir, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.delid = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delid.sizePolicy().hasHeightForWidth())
        self.delid.setSizePolicy(sizePolicy)
        self.delid.setText("")
        self.delid.setDragEnabled(False)
        self.delid.setReadOnly(False)
        self.delid.setObjectName("delid")
        self.gridLayout_8.addWidget(self.delid, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.delseat = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delseat.sizePolicy().hasHeightForWidth())
        self.delseat.setSizePolicy(sizePolicy)
        self.delseat.setObjectName("delseat")
        self.gridLayout_8.addWidget(self.delseat, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        #self.save = QtWidgets.QPushButton(self.groupBox_2)
        #self.save.setObjectName("save")
        #self.gridLayout_5.addWidget(self.save, 1, 1, 1, 1)
        self.upload = QtWidgets.QPushButton(self.groupBox_2)
        self.upload.setObjectName("upload")
        self.gridLayout_5.addWidget(self.upload, 1, 0, 1, 1)
        self.table = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        ###
        df = pd.read_excel('test.xlsx')
        self.table.setColumnCount(df.shape[1])
        self.table.setRowCount(df.shape[0])
        names = df.values.tolist()
        header_labels = df.columns.tolist()
        self.group.clear()
        self.group.addItems(header_labels)
        self.table.setHorizontalHeaderLabels(header_labels)
        for i in range(df.shape[0]):
            for j in range(df.shape[1]):
                item = QtWidgets.QTableWidgetItem(str(df.iloc[i, j]))
                self.table.setItem(i, j, item)
        ###
        self.gridLayout_5.addWidget(self.table, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 3, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setToolTipDuration(-1)
        self.statusBar.setStatusTip("")
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        def updfont(v=None):
            self.fnt.setFamily(self.font.currentText())
            self.fnt.setPointSize(int(self.pix.text()))
            MainWindow.setFont(self.fnt)

        timer = QtCore.QTimer(MainWindow)
        timer.timeout.connect(self.updtime)
        timer.start()

        # ian
        self.group.currentIndexChanged.connect(self.find)
        self.id.valueChanged.connect(self.find)

        self.upload.clicked.connect(self.updnmlst)
        self.draw.clicked.connect(self.rdmdraw)
        self.reset.clicked.connect(self.rdo)
        self.output.clicked.connect(self.out)

        self.delid.textChanged.connect(self.updid)
        self.delseat.textChanged.connect(self.updseat)
        self.changedir.clicked.connect(self.upddir)

        self.font.currentFontChanged.connect(updfont)
        self.pix.textChanged.connect(updfont)
        self.art.currentTextChanged.connect(self.updstyle)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def rdmdraw(self):
        self.upload.setDisabled(True)
        self.delid.setDisabled(True)
        self.delseat.setDisabled(True)
        try:
            exec(f"self.L{self.p[0]}{self.p[1]}.setPalette(NULL)")
        except:
            pass
        self.p = choice(self.cpy)
        self.cpy.remove(self.p)
        self.row.setProperty("value", self.p[0])
        self.col.setProperty("value", self.p[1])
        #self.lb_seat.setPixmap(QtGui.QPixmap(f":/lst/{p[0]}{p[1]}.png"))
        exec(f"self.L{self.p[0]}{self.p[1]}.setText(self.name.text())")
        exec(f"self.L{self.p[0]}{self.p[1]}.setPalette(YELLOW)")
        self.slst.append(self.name.text())
        if len(self.cpy) == 0:
            self.draw.setDisabled(True)
        self.find()

    def updtime(self):
        dt = QtCore.QDateTime.currentDateTime()
        text = dt.toString("yyyy-MM-dd HH:mm:ss")+" | 抽座位小程序 2023 beta4.0 | 测试版"
        self.statusBar.showMessage(text, 0)

    def updnmlst(self):
        global names, cols, header_labels
        self.listname = QtWidgets.QFileDialog.getOpenFileName(filter="Xlsx file (*.xlsx)")[0]
        if self.listname == "":
            return None
        self.progress.setText("当前名册表：" + self.listname)
        self.table.clear()
        df = pd.read_excel(self.listname)
        self.table.setColumnCount(df.shape[1])
        self.table.setRowCount(df.shape[0])
        header_labels = df.columns.tolist()
        self.group.clear()
        self.group.addItems(header_labels)
        #print(df.values.tolist())
        names = df.values.tolist()
        self.table.setHorizontalHeaderLabels(header_labels)
        for i in range(df.shape[0]):
            for j in range(df.shape[1]):
                item = QtWidgets.QTableWidgetItem(str(df.iloc[i, j]))
                self.table.setItem(i, j, item)

    def rdo(self):
        b = QtWidgets.QMessageBox.warning(None, "警告", "该操作将删除所有抽签记录，是否继续？", QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        if b == QtWidgets.QMessageBox.No:
            return None
        self.cpy = list(self.mnu)
        for i in range(1, 8):
            for j in range(1, 8):
                exec(f"self.L{j}{i}.clear()")
                exec(f"self.L{j}{i}.setPalette(NULL)")
        self.slst = list(self._slst)
        self.draw.setDisabled(False)
        self.upload.setDisabled(False)
        self.delid.setDisabled(False)
        self.delseat.setDisabled(False)

    def out(self):
        #dire = QFileDialog.getSaveFileName(None, "选择保存路径", filter="座次表(*.xlsx)")[0]
        #if dire == "":
        #    return None
        if self.filename.text() == "":
            self.filename.setText("座次表")
        dire = self.dir + "/" + self.filename.text() + ".xlsx"
        #try:
        #    f = open(dire)
        #    f.close()
        #    remove(dire)
        #except:
        #    pass
        #workbook = xw.Workbook(dire)
        #worksheet = workbook.add_worksheet("座次表")
        data = [["", "", "", "", "讲台", "", "", "", ""]] + \
            [["" for i in range(9)] for j in range(7)]

        for i in range(1, 8):
            for j in range(1, 8):
                if j >= 6:
                    y = j + 1
                elif j >= 3:
                    y = j
                else:
                    y = j - 1
                exec(f"data[{i}][{y}] = self.L{8-j}{i}.text()")
                #worksheet.write(7 - i, y, exec(f"self.L{i}{j}.text()"))
        #worksheet.write(7, 4, "讲台")
        #workbook.close()
        df = pd.DataFrame(data)
        with pd.ExcelWriter(dire) as writer:
            df.to_excel(writer,
                        sheet_name="座次表"+QtCore.QDateTime.currentDateTime().toString("yyyyMMddhhmmss"),
                        header=False,
                        index=False)

    def find(self, value=None):
        self.name.setText(str(idtoname(self.group.currentText() + self.id.text())))
        if self.name.text() in self.slst or len(self.cpy) == 0:
            self.draw.setDisabled(True)
        else:
            self.draw.setDisabled(False)

    def updid(self):
        s = list(map(idtoname, self.delid.text().split(",")))
        self._slst += s
        self.slst = list(self._slst)
        self.find()

    def updseat(self):
        try:
            s = list(map(lambda x: tuple(map(int, x.split("-"))), self.delseat.text().split(",")))
            self.mnu = [(i, j) for i in range(1, 8) for j in range(1, 8)]
            for i in s:
                if i in self.mnu:
                    self.mnu.remove(i)
        except:
            pass
        self.cpy = list(self.mnu)
        #print(self.cpy)

    def upddir(self):
        self.dir = QtWidgets.QFileDialog.getExistingDirectory()
        self.dldir.setText(self.dir)

    def updstyle(self, style):
        QtWidgets.QApplication.setStyle(style)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", u"抽座位小程序 2023 beta4.0"))
        self.reset.setText(_translate("MainWindow", "重置"))
        self.output.setText(_translate("MainWindow", "导出"))
        self.draw.setText(_translate("MainWindow", "抽签"))
        self.label_5.setText(_translate("MainWindow", "导出文件名"))
        self.label_6.setText(_translate("MainWindow", ".xlsx"))
        self.groupBox.setTitle(_translate("MainWindow", "座次表"))
        self.label_3.setText(_translate("MainWindow", "讲台"))
        #self.jump.setText(_translate("MainWindow", "自动跳转"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "主页"))
        self.groupBox_3.setTitle(_translate("MainWindow", "外观"))
        self.label.setText(_translate("MainWindow", "字体"))
        self.label_2.setText(_translate("MainWindow", "大小"))
        self.label_4.setText(_translate("MainWindow", "样式"))
        #self.art.setItemText(0, _translate("MainWindow", "暂无"))
        self.art.clear()
        self.art.addItems(QtWidgets.QStyleFactory.keys())
        self.groupBox_4.setTitle(_translate("MainWindow", "导出设置"))
        self.label_7.setText(_translate("MainWindow", "导出目录"))
        self.changedir.setText(_translate("MainWindow", "修改"))
        self.groupBox_5.setTitle(_translate("MainWindow", "座位设置"))
        self.delid.setPlaceholderText(_translate("MainWindow", "eg. A3,B4"))
        self.label_8.setText(_translate("MainWindow", "不参与抽座位学生"))
        self.label_9.setText(_translate("MainWindow", "不使用座位号"))
        self.delseat.setPlaceholderText(_translate("MainWindow", "eg. 1-7,2-7"))
        self.groupBox_2.setTitle(_translate("MainWindow", "名册"))
        #self.save.setText(_translate("MainWindow", "保存"))
        self.upload.setText(_translate("MainWindow", "上传"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "设置"))
        self.progress.setText(_translate("MainWindow", "当前名册表："+self.listname))
        self.find()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
